// Database types (will be auto-generated by Supabase CLI later)
// For now, we'll define them manually based on our schema

export type BookCategory = 'trivium' | 'quadrivium';

export type DisciplineType =
  | 'grammar'
  | 'logic'
  | 'rhetoric'
  | 'arithmetic'
  | 'geometry'
  | 'music'
  | 'astronomy';

export type BookCondition = 'new' | 'like_new' | 'very_good' | 'good' | 'acceptable';

export type BookFormat = 'physical' | 'digital' | 'both';

export type AvailabilityStatus = 'available' | 'trading' | 'sold' | 'not_available';

export type WishlistPriority = 'high' | 'medium' | 'low';

export type MatchStatus = 'pending' | 'accepted' | 'declined' | 'completed' | 'expired';

export type SwipeAction = 'like' | 'dislike' | 'superlike' | 'skip';

export type ListingStatus = 'active' | 'sold' | 'cancelled';

export type TransactionStatus =
  | 'pending'
  | 'paid'
  | 'shipped'
  | 'completed'
  | 'refunded'
  | 'cancelled';

export type CourseStatus = 'draft' | 'published' | 'archived';

export type ContentType = 'video' | 'text' | 'mixed' | 'quiz';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          location: string | null;
          disciplines: DisciplineType[];
          reputation_score: number;
          total_trades: number;
          total_sales: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      books: {
        Row: {
          id: string;
          title: string;
          author: string;
          isbn: string | null;
          category: BookCategory;
          discipline: DisciplineType;
          description: string | null;
          cover_url: string | null;
          publisher: string | null;
          publication_year: number | null;
          language: string;
          page_count: number | null;
          goodreads_id: string | null;
          open_library_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['books']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['books']['Insert']>;
      };
      user_books: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          condition: BookCondition;
          format: BookFormat;
          availability: AvailabilityStatus;
          price: number | null;
          trade_preferences: Record<string, any>;
          notes: string | null;
          location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['user_books']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['user_books']['Insert']>;
      };
      wishlists: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          priority: WishlistPriority;
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['wishlists']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['wishlists']['Insert']>;
      };
      book_matches: {
        Row: {
          id: string;
          user_a_id: string;
          user_b_id: string;
          user_a_book_id: string;
          user_b_book_id: string;
          status: MatchStatus;
          match_score: number;
          user_a_accepted: boolean;
          user_b_accepted: boolean;
          created_at: string;
          expires_at: string;
          completed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['book_matches']['Row'], 'id' | 'created_at' | 'expires_at'>;
        Update: Partial<Database['public']['Tables']['book_matches']['Insert']>;
      };
      listings: {
        Row: {
          id: string;
          seller_id: string;
          user_book_id: string;
          price: number;
          shipping_options: Record<string, any>;
          status: ListingStatus;
          views: number;
          featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['listings']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['listings']['Insert']>;
      };
      courses: {
        Row: {
          id: string;
          instructor_id: string;
          title: string;
          slug: string;
          description: string | null;
          category: BookCategory;
          discipline: DisciplineType;
          price: number;
          thumbnail_url: string | null;
          status: CourseStatus;
          student_count: number;
          rating: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['courses']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['courses']['Insert']>;
      };
    };
  };
}
